---
node:
  version: 4

ruby:
  version: 2

python:
  version: 3

dependencies:
  install:
    - openssl
  brew:
  # brew tap
    # sources:
    install:
      - python3
  aptget:
  # apt-key add
    keys:
      - https://dl.yarnpkg.com/debian/pubkey.gpg
  # add-apt-repository
    sources:
      - deb https://dl.yarnpkg.com/debian/ stable main
    install:
      - yarn
  custom:
    name: bower
    desc: install bower dep
    installed?: which dev
    install: bower install

# default installs
# node (npm)
# ruby (bundler)
# golang (glide)
# python (pip)

scripts:
  console:
    desc: blah
    command: bin/rails console

 # import from package.json as well

services:
  - nginx:
    version: 4.0
    image: mysql
  - mysql
  - mongo
  - redis

 docker:
  web:
    image: nginx
    port: 3000


# devctl install
# devctl stop
# devctl restart
# devctl start
# - install
# - docker start

# devctl services start
